### ISSUE TITLE
Cannot see linked guild chat with opposing faction characters

### ISSUE THREAD

**Issue by Klaytonbigsb** [Chalsean/XFaction#388] opened 2024-02-21 00:42 UTC
Hi, the two guilds are both predominantly alliance (GM is alliance), and my horde toons are unable to see the other guild's notifications/chats. However, my alliance toons that are in both guilds can see the other guild notifications, so I don't believe its an error on my end. I've deleted and reinstalled and /reloaded, I've looked at the settings and tinkered with them but unable to make it work. I also inundated my friend's list with many horde and alliance players from both guilds just to be sure.

**Comment by waggz81** [comment] 2024-02-21 00:47
do you have any active bnet links? afaik you'll still need that even if in an "alliance" guild.

**Comment by Klaytonbigsb** [comment] 2024-02-21 00:48
Hi, just clarifying, for active bnet links, you mean players that are online on my friends list? Yes, many are online >10 right now currently on my bnet friends list

**Comment by waggz81** [comment] 2024-02-21 04:01
Yeah if you go to the Links datatext (if you're not sure how to show them, it's the same as the Guild one described in the [FAQ](https://github.com/Chalsean/XFaction/wiki/FAQ) it will list every active bnet link.

**Comment by Chalsean** [comment] 2024-02-21 15:05
Your friends need to be running the addon as well for it to establish a link.  Also can you provide the guild info text that is configuring the two guilds?

**Comment by Klaytonbigsb** [comment] 2024-02-21 19:00
Hi, thanks for the follow-up messages! So is the guild info text the one that I can just generate in xfaction? I was not the one who set it up for my guild, I'm just a member, so want to make sure I can send you that and it would be the same one. If that's the case, here it is:  

XF:LT4UUoimqq0E(k4tivPy6S4Hfn0yxq7kJfA11Gr2Bi6(3hWrjnPANZzMDQFdDUaVN9Z1AAL3wQv5C0XKWXZoTQAQ3DDH2lxl39ZNQfC)guF)fD)6QTpJOZEwiOXGMyELDfQ1Gwk9xjRHorhS8FHgmyyt8jJ4dbkvCJymEqLOPfgHsTpYYBUhM4NDwfS8mfQE9d:XF


I downloaded elvui and I referred to the FAQ and followed it's instructions, went to datatexts, panel, my chatbox, in the dropdown bar I can see "LDB: Guild X". So I assigned it and if I hover over it, I can see both guilds and their members >20+ people with active bnet links in both guilds.

I just tested again right now. On my main character (alliance) in the main guild (alliance), I'm unable to see the opposing faction's chat in the second guild, however I can see their chat if they are the same faction as me, alliance. If I'm on my horde character in the 2nd guild, I'm unable to see any chat of the main guild, at all, whether they are alliance or horde.

**Comment by Klaytonbigsb** [comment] 2024-02-21 19:06
Actually, interestingly enough, if I check the datatext from my horde character, LDB Guild X appears in the dropdown, however I cannot see anything, a roster does not appear when I hover over it like it does on my alliance character. *scratches head*

**Comment by Chalsean** [comment] 2024-02-21 21:47
That means its running into an issue of some sort during startup.  For giggles, try manually creating the channel with the password.  It should exist on both Horde and Alliance side.

If you install addons BugSack, BugGrabber and DebugLog it will help troubleshoot.  You should see a sack (bugsack) and yellow fist (debuglog) minimap icons.  Two things to check are if the sack color is red that means some addon is throwing, potentially xfaction.  The debuglog is useful for troubleshooting issues, but you'll need to set the verbosity level to at least 4 (Addons / Options / XFaction / Debug / Verbosity Level)

**Comment by Chalsean** [comment] 2024-02-21 21:48
Worst comes to worst, I can always jump a toon in your guild and troubleshoot tonight.

**Comment by Klaytonbigsb** [comment] 2024-02-21 22:26
Manually joined channel, no changes. Still no active links on horde toon. Installed bugsack, buggrabber, debuglog. Bugsack is green. Deleted the xfaction, exited the game, installed xfaction, reloaded ui, horde toon still nothing; alliance toons have many active links

**Comment by Chalsean** [comment] 2024-02-21 23:40
Thought occurred to me, flag one of the guild as horde and one alliance,
instead of both alliance

**Comment by Klaytonbigsb** [comment] 2024-02-22 08:08
I set one of them to horde, made no difference. It looks like this issue isn't isolated to me, my other guildmates on their horde toons also have no active bnet links also but they do on their alliance toons. I really love the idea of you troubleshooting it in real time -- do you think we can setup a time for when you're free?

**Comment by Chalsean** [comment] 2024-02-22 15:00
Yeah I can make myself available tonight after 16:00 server

**Comment by Klaytonbigsb** [comment] 2024-02-22 17:47
Yes please!! My battletag is Nabilyoo#1253, server is Stormrage

**Comment by Chalsean** [comment] 2024-02-24 23:21
There is a couple bugs that exist from legacy code when guilds were faction isolated.  If all guilds on a realm are configured as the same faction, it switches to Greenwall like functionality.  Fix is to ensure one of the guilds is of an opposite faction.  Will work on a code fix but this one will be in the core networking logic.  Will probably bundle this fix with 5.0 rewrite.

**Comment by waggz81** [comment] 2024-03-19 14:57
@Chalsean since it appears we might be having this issue as well would it be worthwhile troubleshooting to create an alliance guild on Illidan and add it to the confederate even if we don't put anybody in it aside from the guild charter?

**Comment by Chalsean** [comment] 2024-03-19 16:08
This bug was specific to configuration/setup of a new confederate.  For
your situation I'll have to troubleshoot.  My guess is that I'll need to
update the code to recognize there's only 1 guild on the realm and switch
to using GUILD channel instead of custom channel.

**Comment by Chalsean** [comment] 2024-05-31 13:31
im going to close this ticket out as a duplicate of case https://github.com/Chalsean/XFaction/issues/399.  the solution is the same for both

**Closed by Chalsean** 2024-05-31 13:31 UTC
Labels: enhancement, large effort
